"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Bell, BriefcaseBusiness, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Home, LoaderCircle, LogOut, MapPin, MessageSquareText, Plus, RefreshCw, Save, Settings2, Star, X, XCircle } from "lucide-react";
import { API_BASE, partnerHeaders, PARTNER_TOKEN_KEY } from "@/features/auth/partner-auth";

type Profile={fullName:string;phone:string;email:string;partnerType:"Individual"|"Team";teamName?:string;teamSize:number;isAvailable:boolean;serviceAddress:string;averageRating:number;completedBookings:number;walletBalance:number;services:string[]};
type Rule={dayOfWeek:string;startTime:string;endTime:string;isActive:boolean};type Override={date:string;isUnavailable:boolean;startTime:string|null;endTime:string|null;note?:string};
type Scheduled={id:string;code:string;contractCode:string|null;occurrenceNumber:number|null;totalOccurrences:number|null;addressSnapshot:string;scheduledStartAt:string;scheduledEndAt:string;status:string;customerRequest:string|null;taskerConfirmedAt:string|null;arrivedAt:string|null;startedAt:string|null;completionReportedAt:string|null};
type Invitation={id:string;status:string;invitedAt:string;expiresAt:string;distanceMetersAtInvitation:number|null;code:string;service:string;addressSnapshot:string;scheduledStartAt:string;scheduledEndAt:string;requiredWorkers:number;estimatedTotal:number;bookingStatus:string;customerRequest:string|null};
type Notification={id:string;title:string;message:string;isRead:boolean;createdAt:string};
type Review={id:string;rating:number;comment:string|null;createdAt:string;bookingCode:string;service:string;customerName:string};
const days=[{value:"Monday",label:"Thứ Hai"},{value:"Tuesday",label:"Thứ Ba"},{value:"Wednesday",label:"Thứ Tư"},{value:"Thursday",label:"Thứ Năm"},{value:"Friday",label:"Thứ Sáu"},{value:"Saturday",label:"Thứ Bảy"},{value:"Sunday",label:"Chủ Nhật"}];
const money=(n:number)=>new Intl.NumberFormat("vi-VN").format(n)+"đ";
const dateTime24=(value:string)=>new Date(value).toLocaleString("vi-VN",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:false});
const time24=(value:string)=>new Date(value).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit",hour12:false});

export default function PartnerPortal(){
 const router=useRouter();const [tab,setTab]=useState<"home"|"schedule"|"jobs"|"reviews"|"notifications">("home");const [profile,setProfile]=useState<Profile|null>(null);const [rules,setRules]=useState<Rule[]>([]);const [overrides,setOverrides]=useState<Override[]>([]);const [bookings,setBookings]=useState<Scheduled[]>([]);const [invitations,setInvitations]=useState<Invitation[]>([]);const [notifications,setNotifications]=useState<Notification[]>([]);const [reviews,setReviews]=useState<Review[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
 const request=useCallback(async(path:string,options?:RequestInit)=>{const response=await fetch(`${API_BASE}${path}`,{...options,headers:{...partnerHeaders(),...(options?.body?{"Content-Type":"application/json"}:{})}});if(response.status===401){localStorage.removeItem(PARTNER_TOKEN_KEY);router.replace("/dang-nhap");throw new Error("Phiên đăng nhập đã hết hạn.")}const data=response.status===204?{}:await response.json();if(!response.ok){const validation=data.errors?Object.values(data.errors).flat().join(" "):null;throw new Error(data.message??validation??"Không thể xử lý yêu cầu.")}return data},[router]);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [me,calendar,jobs,alerts,reviewItems]=await Promise.all([request("/api/partner/me"),request("/api/partner/me/availability"),request("/api/partner/me/invitations"),request("/api/partner/me/notifications"),request("/api/partner/me/reviews")]);setProfile(me);setRules(calendar.rules.map((x:Rule)=>({...x,startTime:x.startTime.slice(0,5),endTime:x.endTime.slice(0,5)})));setOverrides(calendar.overrides.map((x:Override)=>({...x,startTime:x.startTime?.slice(0,5)??null,endTime:x.endTime?.slice(0,5)??null})));setBookings(calendar.bookings);setInvitations(jobs);setNotifications(alerts);setReviews(reviewItems)}catch(reason){setError(reason instanceof TypeError?"Không thể kết nối backend.":reason instanceof Error?reason.message:"Không thể tải dữ liệu.")}finally{setLoading(false)}},[request]);
 useEffect(()=>{if(!localStorage.getItem(PARTNER_TOKEN_KEY)){router.replace("/dang-nhap");return}void load()},[load,router]);
 const pending=useMemo(()=>invitations.filter(x=>x.status==="Invited"&&new Date(x.expiresAt)>new Date()),[invitations]);
 const visibleInvitations=useMemo(()=>invitations.filter(x=>x.status!=="Rejected"),[invitations]);
 const activeBookings=useMemo(()=>bookings.filter(x=>x.status!=="Completed"),[bookings]);
 function ruleFor(day:string){return rules.find(x=>x.dayOfWeek===day)}
 function toggleDay(day:string){const existing=ruleFor(day);setRules(current=>existing?current.filter(x=>x.dayOfWeek!==day):[...current,{dayOfWeek:day,startTime:"08:00",endTime:"17:00",isActive:true}])}
 function updateRule(day:string,key:"startTime"|"endTime",value:string){setRules(current=>current.map(x=>x.dayOfWeek===day?{...x,[key]:value}:x))}
 function addOverride(){setOverrides(current=>[...current,{date:new Date(Date.now()+86400000).toISOString().slice(0,10),isUnavailable:true,startTime:null,endTime:null,note:""}])}
 async function saveSchedule(){setSaving(true);setError("");setMessage("");const withSeconds=(value:string|null)=>value&&value.length===5?`${value}:00`:value;try{const data=await request("/api/partner/me/availability",{method:"PUT",body:JSON.stringify({rules:rules.map(x=>({...x,startTime:withSeconds(x.startTime),endTime:withSeconds(x.endTime)})),overrides:overrides.map(x=>({...x,startTime:withSeconds(x.startTime),endTime:withSeconds(x.endTime)}))})});setMessage(data.message);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Không thể lưu lịch.")}finally{setSaving(false)}}
 async function toggleAvailable(){if(!profile)return;try{const data=await request("/api/partner/me/job-invitations",{method:"PATCH",body:JSON.stringify({enabled:!profile.isAvailable})});setProfile({...profile,isAvailable:data.isAvailable});setMessage(data.message);if(data.invitationsCreated>0)await load()}catch(reason){setError(reason instanceof Error?reason.message:"Không thể cập nhật.")}}
 async function respond(id:string,accept:boolean){setSaving(true);try{const data=await request(`/api/partner/me/invitations/${id}/respond`,{method:"POST",body:JSON.stringify({accept})});setMessage(data.message);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Không thể phản hồi.")}finally{setSaving(false)}}
 async function cancelBooking(id:string){if(!confirm("Bạn chắc chắn muốn hủy nhận đơn này? Hệ thống sẽ tìm người thay thế ngay."))return;setSaving(true);try{const data=await request(`/api/partner/me/bookings/${id}/cancel`,{method:"POST",body:JSON.stringify({reason:"Đối tác không thể tiếp tục thực hiện lịch đã nhận."})});setMessage(data.message);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Không thể hủy nhận việc.")}finally{setSaving(false)}}
 async function advanceBooking(id:string,action:"confirm"|"arrive"|"start"|"complete"){setSaving(true);try{const data=await request(`/api/partner/me/bookings/${id}/${action}`,{method:"POST"});setMessage(data.message);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Không thể cập nhật trạng thái.")}finally{setSaving(false)}}
 async function logout(){try{await request("/api/partner/auth/logout",{method:"POST"})}catch{}localStorage.removeItem(PARTNER_TOKEN_KEY);router.replace("/dang-nhap")}
 if(loading&&!profile)return <main className="partner-portal-loading"><LoaderCircle className="spin"/>Đang tải trang đối tác...</main>;
 return <main className="partner-portal"><aside><div className="portal-brand"><BriefcaseBusiness/>Every<b>Care</b></div><nav><button className={tab==="home"?"active":""} onClick={()=>setTab("home")}><Home/>Tổng quan</button><button className={tab==="schedule"?"active":""} onClick={()=>setTab("schedule")}><CalendarDays/>Lịch làm việc</button><button className={tab==="jobs"?"active":""} onClick={()=>setTab("jobs")}><BriefcaseBusiness/>Việc phù hợp {pending.length>0&&<i>{pending.length}</i>}</button><button className={tab==="reviews"?"active":""} onClick={()=>setTab("reviews")}><MessageSquareText/>Đánh giá</button><button className={tab==="notifications"?"active":""} onClick={()=>setTab("notifications")}><Bell/>Thông báo</button></nav><button className="portal-logout" onClick={()=>void logout()}><LogOut/>Đăng xuất</button></aside><section className="portal-main"><header><div><small>KHU VỰC ĐỐI TÁC</small><strong>{profile?.teamName||profile?.fullName}</strong></div><button onClick={()=>void load()}><RefreshCw className={loading?"spin":""}/></button></header><div className="portal-content">{error&&<div className="portal-alert error">{error}<button onClick={()=>setError("")}><X/></button></div>}{message&&<div className="portal-alert success"><Check/>{message}<button onClick={()=>setMessage("")}><X/></button></div>}
  {tab==="home"&&profile&&<><div className="portal-title"><span>Tổng quan</span><h1>Chào {profile.fullName}</h1><p>Theo dõi công việc đang thực hiện và trạng thái nhận việc của bạn.</p></div><div className="portal-stats"><article><BriefcaseBusiness/><span><small>Lời mời còn hiệu lực</small><strong>{pending.length}</strong></span></article><article><CalendarDays/><span><small>Đơn đang thực hiện</small><strong>{activeBookings.length}</strong></span></article><article><Settings2/><span><small>Ví Tasker</small><strong>{money(profile.walletBalance)}</strong></span></article></div><section className="availability-toggle"><div><span className={profile.isAvailable?"online":"offline"}/><div><h2>Nhận lời mời công việc mới</h2><p>{profile.isAvailable?"Đang bật — lời mời vẫn được lưu khi bạn đóng website.":"Đang tắt — các đơn đã nhận không bị hủy."}</p></div></div><button className={profile.isAvailable?"toggle on":"toggle"} onClick={()=>void toggleAvailable()}><i/></button></section><ActiveJobs bookings={activeBookings} saving={saving} onAdvance={advanceBooking} onCancel={cancelBooking}/></>}
  {tab==="schedule"&&<><div className="portal-title"><span>Lịch làm việc</span><h1>Lịch công việc theo tuần</h1><p>Chọn từng ngày để xem lịch sắp tới hoặc các công việc đã hoàn thành.</p></div><WeeklyJobs bookings={bookings}/><section className="portal-card schedule-editor"><h2>Đăng ký thời gian rảnh (24 giờ)</h2>{days.map(day=>{const rule=ruleFor(day.value);return <div className="weekday-row" key={day.value}><label><input type="checkbox" checked={!!rule} onChange={()=>toggleDay(day.value)}/><strong>{day.label}</strong></label>{rule?<div><Time24Field value={rule.startTime} onChange={value=>updateRule(day.value,"startTime",value)}/><span>đến</span><Time24Field value={rule.endTime} onChange={value=>updateRule(day.value,"endTime",value)}/></div>:<small>Không làm việc</small>}</div>})}</section><section className="portal-card override-editor"><div className="card-heading"><div><h2>Ngày nghỉ hoặc giờ đặc biệt</h2><p>Thiết lập này sẽ thay thế lịch tuần ở đúng ngày đã chọn.</p></div><button onClick={addOverride}><Plus/>Thêm ngày</button></div>{overrides.map((item,index)=><div className="override-row" key={index}><input type="date" value={item.date} onChange={e=>setOverrides(current=>current.map((x,i)=>i===index?{...x,date:e.target.value}:x))}/><label><input type="checkbox" checked={item.isUnavailable} onChange={e=>setOverrides(current=>current.map((x,i)=>i===index?{...x,isUnavailable:e.target.checked,startTime:e.target.checked?null:"08:00",endTime:e.target.checked?null:"17:00"}:x))}/>Nghỉ cả ngày</label>{!item.isUnavailable&&<><Time24Field value={item.startTime??"08:00"} onChange={value=>setOverrides(current=>current.map((x,i)=>i===index?{...x,startTime:value}:x))}/><span>—</span><Time24Field value={item.endTime??"17:00"} onChange={value=>setOverrides(current=>current.map((x,i)=>i===index?{...x,endTime:value}:x))}/></>}<button onClick={()=>setOverrides(current=>current.filter((_,i)=>i!==index))}><XCircle/></button></div>)}</section><button className="button portal-save" disabled={saving} onClick={()=>void saveSchedule()}>{saving?<LoaderCircle className="spin"/>:<Save/>}Lưu lịch làm việc</button></>}
  {tab==="jobs"&&<><div className="portal-title"><span>Việc phù hợp</span><h1>Lời mời công việc</h1><p>Công việc đã từ chối được loại khỏi danh sách này.</p></div><div className="invitation-list">{visibleInvitations.map(item=><article className="invitation-card" key={item.id}><header><span className={`invitation-status ${item.status.toLowerCase()}`}>{item.status==="Invited"?"Chờ phản hồi":item.status}</span><small>Hết hạn {dateTime24(item.expiresAt)}</small></header><h2>{item.service}</h2><p><MapPin/>{item.addressSnapshot}</p><p><Clock3/>{dateTime24(item.scheduledStartAt)} — {time24(item.scheduledEndAt)}</p>{item.customerRequest&&<p><BriefcaseBusiness/>Yêu cầu: {item.customerRequest}</p>}<div><span>{item.requiredWorkers} người</span><span>{item.distanceMetersAtInvitation?`${(item.distanceMetersAtInvitation/1000).toFixed(1)} km`:"Chưa rõ khoảng cách"}</span><strong>{money(item.estimatedTotal)}</strong></div>{item.status==="Invited"&&new Date(item.expiresAt)>new Date()&&<footer><button disabled={saving} onClick={()=>void respond(item.id,false)}>Từ chối</button><button className="button" disabled={saving} onClick={()=>void respond(item.id,true)}>Đồng ý nhận</button></footer>}</article>)}{!visibleInvitations.length&&<div className="portal-empty">Chưa có lời mời phù hợp.</div>}</div></>}
  {tab==="reviews"&&profile&&<><div className="portal-title"><span>Uy tín Tasker</span><h1>Đánh giá từ khách hàng</h1><p>Theo dõi số sao và nhận xét sau mỗi công việc đã hoàn thành.</p></div><PartnerReviews reviews={reviews} averageRating={profile.averageRating}/></>}
  {tab==="notifications"&&<><div className="portal-title"><span>Thông báo</span><h1>Thông báo của bạn</h1><p>Lời mời vẫn nằm ở đây khi bạn đăng xuất hoặc đóng website.</p></div><section className="portal-card notification-list">{notifications.map(item=><div key={item.id} className={item.isRead?"":"unread"}><Bell/><span><strong>{item.title}</strong><p>{item.message}</p><small>{new Date(item.createdAt).toLocaleString("vi-VN")}</small></span></div>)}{!notifications.length&&<div className="portal-empty">Chưa có thông báo.</div>}</section></>}
 </div></section></main>;
}

function ActiveJobs({bookings,saving,onAdvance,onCancel}:{bookings:Scheduled[];saving:boolean;onAdvance:(id:string,action:"confirm"|"arrive"|"start"|"complete")=>Promise<void>;onCancel:(id:string)=>Promise<void>}){
 return <section className="portal-card"><h2>Công việc đang thực hiện</h2>{bookings.length?bookings.map(item=><div className="scheduled-job lifecycle-job" key={item.id}><CalendarDays/><span><strong>{item.contractCode?`${item.contractCode} · Lượt ${item.occurrenceNumber}/${item.totalOccurrences}`:item.code} • {dateTime24(item.scheduledStartAt)}</strong><small>{item.addressSnapshot}</small>{item.customerRequest&&<small>Yêu cầu: {item.customerRequest}</small>}</span><b>{statusText(item)}</b><div className="job-actions">{item.status==="Assigned"&&!item.taskerConfirmedAt&&<button onClick={()=>void onAdvance(item.id,"confirm")}>Xác nhận lịch</button>}{item.status==="Assigned"&&item.taskerConfirmedAt&&<button onClick={()=>void onAdvance(item.id,"arrive")}>Tasker đã đến</button>}{item.status==="PartnerTravelling"&&<button onClick={()=>void onAdvance(item.id,"start")}>Bắt đầu làm</button>}{item.status==="InProgress"&&<button onClick={()=>void onAdvance(item.id,"complete")}>Báo hoàn thành</button>}{(item.status==="Assigned"||item.status==="PartnerTravelling")&&<button className="cancel-job" disabled={saving} onClick={()=>void onCancel(item.id)}>Hủy nhận</button>}</div></div>):<div className="portal-empty">Hiện không có công việc đang thực hiện.</div>}</section>;
}

function WeeklyJobs({bookings}:{bookings:Scheduled[]}){
 const today=useMemo(()=>{const value=new Date();value.setHours(0,0,0,0);return value},[]);
 const [weekOffset,setWeekOffset]=useState(0);
 const [selectedIndex,setSelectedIndex]=useState(()=>{const day=today.getDay();return day===0?6:day-1});
 const week=useMemo(()=>{const monday=new Date(today);monday.setDate(today.getDate()-(today.getDay()===0?6:today.getDay()-1)+(weekOffset*7));return Array.from({length:7},(_,index)=>{const date=new Date(monday);date.setDate(monday.getDate()+index);return date})},[today,weekOffset]);
 const selected=week[selectedIndex];
 const selectedJobs=bookings.filter(item=>{const date=new Date(item.scheduledStartAt);return date.getFullYear()===selected.getFullYear()&&date.getMonth()===selected.getMonth()&&date.getDate()===selected.getDate()});
 return <section className="portal-card weekly-jobs"><div className="week-heading"><div><h2>Lịch 7 ngày</h2><p>{week[0].toLocaleDateString("vi-VN")} — {week[6].toLocaleDateString("vi-VN")}</p></div><div><button aria-label="Tuần trước" onClick={()=>setWeekOffset(value=>value-1)}><ChevronLeft/></button><button onClick={()=>{setWeekOffset(0);const day=today.getDay();setSelectedIndex(day===0?6:day-1)}}>Tuần này</button><button aria-label="Tuần sau" onClick={()=>setWeekOffset(value=>value+1)}><ChevronRight/></button></div></div><div className="week-days">{week.map((date,index)=>{const count=bookings.filter(item=>new Date(item.scheduledStartAt).toDateString()===date.toDateString()).length;return <button className={index===selectedIndex?"active":""} onClick={()=>setSelectedIndex(index)} key={date.toISOString()}><small>{date.toLocaleDateString("vi-VN",{weekday:"short"})}</small><strong>{date.getDate()}</strong>{count>0&&<i>{count}</i>}</button>})}</div><div className="day-jobs"><h3>{selected.toLocaleDateString("vi-VN",{weekday:"long",day:"2-digit",month:"2-digit",year:"numeric"})}</h3>{selectedJobs.length?selectedJobs.map(item=><article key={item.id}><span className={`day-job-status ${item.status.toLowerCase()}`}>{item.status==="Completed"?"Đã hoàn thành":statusText(item)}</span><div><strong>{item.code} · {time24(item.scheduledStartAt)}–{time24(item.scheduledEndAt)}</strong><p>{item.addressSnapshot}</p></div></article>):<div className="portal-empty">Ngày này chưa có công việc.</div>}</div></section>;
}

function Time24Field({value,onChange}:{value:string;onChange:(value:string)=>void}){
 const [hour="00",minute="00"]=value.split(":");
 return <span className="time-24-field"><select aria-label="Giờ" value={hour} onChange={event=>onChange(`${event.target.value}:${minute}`)}>{Array.from({length:24},(_,index)=>String(index).padStart(2,"0")).map(item=><option key={item}>{item}</option>)}</select><b>:</b><select aria-label="Phút" value={minute} onChange={event=>onChange(`${hour}:${event.target.value}`)}>{Array.from({length:60},(_,index)=>String(index).padStart(2,"0")).map(item=><option key={item}>{item}</option>)}</select></span>;
}

function statusText(item:Scheduled){return item.status==="Assigned"?(item.taskerConfirmedAt?"Đã xác nhận lịch":"Cần xác nhận"):item.status==="PartnerTravelling"?"Tasker đã đến":item.status==="InProgress"?"Đang thực hiện":item.status==="AwaitingCustomerConfirmation"?"Chờ khách xác nhận":item.status==="Completed"?"Đã hoàn thành":item.status}

function PartnerReviews({reviews,averageRating}:{reviews:Review[];averageRating:number}){
 return <section className="portal-card partner-reviews"><div className="partner-reviews-head"><div><h2>Đánh giá từ khách hàng</h2><p>Điểm trung bình <strong>{averageRating.toFixed(1)}/5</strong> · {reviews.length} đánh giá</p></div><MessageSquareText/></div>{reviews.length?<div className="partner-review-list">{reviews.slice(0,6).map(review=><article key={review.id}><header><span>{Array.from({length:5},(_,index)=><Star key={index} className={index<review.rating?"active":""}/>)}</span><b>{review.rating}/5</b></header>{review.comment?<p>“{review.comment}”</p>:<p className="no-comment">Khách hàng không để lại nhận xét.</p>}<footer><strong>{review.customerName}</strong><span>{review.service} · {review.bookingCode}</span><time>{new Date(review.createdAt).toLocaleDateString("vi-VN")}</time></footer></article>)}</div>:<div className="portal-empty">Bạn chưa nhận được đánh giá nào.</div>}</section>;
}
