"use client";

import dynamic from "next/dynamic";
import { FormEvent, useEffect, useState } from "react";
import { Check, Home, MapPin, Plus, Save, X } from "lucide-react";
import { useAuth } from "@/components/auth-provider";
import type { MapLocation } from "@/components/partner-location-map";

const LocationMap=dynamic(()=>import("@/components/partner-location-map"),{ssr:false});
type SavedAddress={id:string;label:string;details:string;note?:string;latitude:number;longitude:number};

export function AddressStep({value,error,onChange,onLocationChange,onClearError}:{value:string;error:string;onChange:(value:string)=>void;onLocationChange:(value:MapLocation|null)=>void;onClearError:()=>void}){
 const {customer}=useAuth();const [addresses,setAddresses]=useState<SavedAddress[]>([]);const [hydrated,setHydrated]=useState(false);const [showForm,setShowForm]=useState(false);const [label,setLabel]=useState("Nhà riêng");const [details,setDetails]=useState("");const [note,setNote]=useState("");const [location,setLocation]=useState<MapLocation|null>(null);const [formError,setFormError]=useState("");
 const storageKey=customer?`everycare_addresses_${customer.id}`:"";const format=(address:SavedAddress)=>`${address.label} • ${address.details}`;
 useEffect(()=>{if(!storageKey)return;try{const saved=JSON.parse(localStorage.getItem(storageKey)??"[]") as SavedAddress[];setAddresses(saved);if(saved.length&&!value){onChange(format(saved[0]));onLocationChange(Number.isFinite(saved[0].latitude)?{latitude:saved[0].latitude,longitude:saved[0].longitude}:null);}if(!saved.length)setShowForm(true);}catch{setAddresses([]);setShowForm(true)}setHydrated(true);},[storageKey]);
 useEffect(()=>{if(hydrated&&storageKey)localStorage.setItem(storageKey,JSON.stringify(addresses));},[addresses,hydrated,storageKey]);
 function addAddress(event:FormEvent){event.preventDefault();const clean=details.trim().replace(/\s+/g," ");if(clean.length<10){setFormError("Vui lòng nhập đầy đủ số nhà, đường và phường/xã.");return}if(!location){setFormError("Vui lòng chọn đúng vị trí địa chỉ trên bản đồ.");return}const item:SavedAddress={id:crypto.randomUUID(),label,details:clean,note:note.trim()||undefined,...location};setAddresses(current=>[...current,item]);onChange(format(item));onLocationChange(location);onClearError();setDetails("");setNote("");setLabel("Nhà riêng");setLocation(null);setFormError("");setShowForm(false);}
 function remove(address:SavedAddress){if(!confirm(`Bạn có chắc muốn xóa địa chỉ “${address.label} — ${address.details}” không?`))return;const rest=addresses.filter(x=>x.id!==address.id);setAddresses(rest);if(value===format(address)){onChange(rest.length?format(rest[0]):"");onLocationChange(rest.length&&Number.isFinite(rest[0].latitude)?{latitude:rest[0].latitude,longitude:rest[0].longitude}:null);}}
 return <div className="wizard-panel address-step"><h2>Chọn nơi cần dọn</h2><p>Nhập địa chỉ và xác nhận trên bản đồ để hệ thống tìm đối tác ở gần chính xác hơn.</p>
  <div className="saved-address-list">{addresses.map(address=>{const selected=value===format(address);return <div className={selected?"saved-address selected":"saved-address"} key={address.id} onClick={()=>{onChange(format(address));onLocationChange(Number.isFinite(address.latitude)?{latitude:address.latitude,longitude:address.longitude}:null);onClearError();}} role="radio" aria-checked={selected}><span className="select-icon"><MapPin/></span><span className="address-copy"><strong>{address.label}</strong><small>{address.details}</small>{address.note&&<em>Ghi chú: {address.note}</em>}{!Number.isFinite(address.latitude)&&<em className="missing-coordinates">Cần thêm lại để xác nhận bản đồ</em>}</span>{selected&&<Check className="select-check"/>}<button type="button" className="delete-address" aria-label={`Xóa địa chỉ ${address.label}`} onClick={event=>{event.stopPropagation();remove(address)}}><X/></button></div>})}</div>
  {!addresses.length&&hydrated&&!showForm&&<div className="empty-address"><Home/><strong>Bạn chưa có địa chỉ đã lưu</strong><span>Thêm địa chỉ đầu tiên để tiếp tục đặt dịch vụ.</span></div>}{error&&<div className="address-error" role="alert">{error}</div>}
  {!showForm?<button type="button" className="add-card" onClick={()=>setShowForm(true)}><Plus/><span><strong>Thêm địa chỉ mới</strong><small>Nhập địa chỉ mới của TP.HCM và chọn vị trí trên bản đồ</small></span></button>:<form className="new-address-form" onSubmit={addAddress}><div className="new-address-head"><div><strong>Thêm địa chỉ mới</strong><small>Điền địa chỉ rồi xác nhận đúng vị trí trên bản đồ</small></div><button type="button" onClick={()=>{setShowForm(false);setFormError("")}}><X/></button></div><div className="new-address-grid"><label><span>Loại địa chỉ</span><select value={label} onChange={e=>setLabel(e.target.value)}><option>Nhà riêng</option><option>Căn hộ</option><option>Văn phòng</option><option>Khác</option></select></label><label className="full"><span>Địa chỉ mới</span><textarea value={details} onChange={e=>{setDetails(e.target.value);setFormError("")}} placeholder="Ví dụ: 24 Nguyễn Văn Cừ, P. Chợ Quán, TP.HCM"/></label><label className="full"><span>Ghi chú cho người dọn <i>(không bắt buộc)</i></span><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Số tầng, tên tòa nhà, cách tìm nhà..."/></label></div><LocationMap value={location} onChange={next=>{setLocation(next);setFormError("")}}/>{formError&&<small className="address-form-error">{formError}</small>}<div className="new-address-actions"><button type="button" onClick={()=>setShowForm(false)}>Hủy</button><button className="button" type="submit"><Save/> Lưu và sử dụng địa chỉ</button></div></form>}
 </div>;
}
