"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { BarChart3, Bell, Boxes, ChevronRight, CircleDollarSign, ClipboardList, Edit3, LayoutDashboard, LoaderCircle, Lock, LogOut, Menu, MoreHorizontal, PackagePlus, Plus, RefreshCw, Search, Settings, ShieldCheck, Sparkles, Trash2, Unlock, UserCheck, Users, X } from "lucide-react";
import { useAdminAuth } from "@/components/admin-auth-provider";
import { professionalInfo, services, WorkDetails } from "@/lib/mock-data";
import { AdminPartnerApplications } from "@/components/admin-partner-applications";
import { AdminCustomersManager } from "@/components/admin-customers-manager";
import { utilityServices } from "@/lib/service-catalog";
import { deepCleaningBenefits, deepCleaningLongDescription, professionalCleaningBenefits, professionalCleaningLongDescription, roomServiceBenefits, roomServiceLongDescription } from "@/lib/service-description-content";

type Status = "active" | "locked";
type Customer = { id:string; name:string; phone:string; email:string; orders:number; status:Status; joined:string };
type Partner = { id:string; name:string; phone:string; kind:"Cá nhân"|"Đội nhóm"; services:string; status:Status|"pending"; members:number };
type Plan = { id:string; name:string; price:number; details:string; status:Status; workDetails?:WorkDetails };
type ServiceGroup = { id:string; name:string; description:string; longDescription?:string; benefits?:{title:string;description:string}[]; status:Status; plans:Plan[]; process?:string[]; tools?:{name:string;description:string}[] };
type Section = "dashboard"|"orders"|"services"|"customers"|"partners";
type Editor = { kind:"customer"|"partner"|"group"|"plan"; item?:Customer|Partner|ServiceGroup|Plan; groupId?:string } | null;

const initialCustomers: Customer[] = [
  {id:"KH001",name:"Nguyễn Minh Anh",phone:"0901234567",email:"minhanh@gmail.com",orders:12,status:"active",joined:"12/08/2026"},
  {id:"KH002",name:"Trần Quốc Huy",phone:"0938123456",email:"quochuy@gmail.com",orders:5,status:"active",joined:"29/08/2026"},
  {id:"KH003",name:"Lê Ngọc Thảo",phone:"0987654321",email:"ngocthao@gmail.com",orders:8,status:"locked",joined:"02/09/2026"},
  {id:"KH004",name:"Phạm Mỹ Linh",phone:"0912444555",email:"mylinh@gmail.com",orders:3,status:"active",joined:"10/09/2026"},
];
const initialPartners: Partner[] = [
  {id:"DT001",name:"Nguyễn Thị Ngọc",phone:"0909888777",kind:"Cá nhân",services:"Dọn dẹp nhà cửa, Tổng vệ sinh",status:"active",members:1},
  {id:"DT002",name:"Đội Thanh Tâm",phone:"0933777888",kind:"Đội nhóm",services:"Tổng vệ sinh, Chuyên nghiệp",status:"active",members:4},
  {id:"DT003",name:"Đội Phúc An",phone:"0988222111",kind:"Đội nhóm",services:"Chuyên nghiệp",status:"pending",members:5},
  {id:"DT004",name:"Trần Văn Bình",phone:"0903555666",kind:"Cá nhân",services:"Dọn dẹp nhà cửa",status:"locked",members:1},
];
const initialGroups: ServiceGroup[] = [
  {id:"room",name:"Dọn dẹp nhà cửa",description:"Dọn nhanh theo giờ cho căn hộ và nhà ở.",longDescription:roomServiceLongDescription,benefits:roomServiceBenefits,status:"active",plans:[
    {id:"r1",name:"Gói 1 giờ",price:120000,details:"Tối đa 30m² • 1 người",status:"active"},{id:"r2",name:"Gói 2 giờ",price:210000,details:"Tối đa 55m² • 1 người",status:"active"},{id:"r3",name:"Gói 3 giờ",price:300000,details:"Tối đa 85m² • 1 người",status:"active"},{id:"r4",name:"Gói 4 giờ",price:380000,details:"Tối đa 105m² • 1 người",status:"active"}]},
  {id:"deep",name:"Tổng vệ sinh",description:"Làm sạch chuyên sâu toàn bộ không gian với đội nhóm 2–4 Tasker.",longDescription:deepCleaningLongDescription,benefits:deepCleaningBenefits,status:"active",plans:[
    {id:"d1",name:"Căn hộ 60m²",price:690000,details:"2 người • 3 giờ",status:"active"},{id:"d2",name:"Nhà 80m²",price:890000,details:"2 người • 4 giờ",status:"active"},{id:"d3",name:"Nhà 100m²",price:1090000,details:"3 người • 3 giờ",status:"active"}]},
  {id:"office",name:"Dọn dẹp văn phòng định kỳ",description:"Nhân sự theo buổi, theo ngày hoặc lịch cố định hằng tháng.",status:"active",plans:[
    {id:"o100",name:"Văn phòng tối đa 100m²",price:260000,details:"1 người • 2 giờ",status:"active"},{id:"o150",name:"Văn phòng tối đa 150m²",price:360000,details:"1 người • 3 giờ",status:"active"},{id:"o200",name:"Văn phòng tối đa 200m²",price:450000,details:"1 người • 4 giờ",status:"active"},{id:"o250",name:"Văn phòng tối đa 250m²",price:550000,details:"1 người • 5 giờ",status:"active"},{id:"o300",name:"Văn phòng tối đa 300m²",price:690000,details:"2 người • 3 giờ",status:"active"},{id:"o400",name:"Văn phòng tối đa 400m²",price:880000,details:"2 người • 4 giờ",status:"active"},{id:"o500",name:"Văn phòng tối đa 500m²",price:1050000,details:"2 người • 5 giờ",status:"active"},{id:"o750",name:"Văn phòng tối đa 750m²",price:1550000,details:"3 người • 5 giờ",status:"active"},{id:"o900",name:"Văn phòng tối đa 900m²",price:1850000,details:"3 người • 6 giờ",status:"active"}]},
  {id:"hospitality",name:"Dọn dẹp buồng phòng",description:"Dọn phòng cho khách sạn, homestay, căn hộ dịch vụ và villa.",status:"active",plans:[
    {id:"hotel-single",name:"Khách sạn/Homestay • Phòng đơn",price:90000,details:"Tối đa 15m²",status:"active"},{id:"hotel-double",name:"Khách sạn/Homestay • Phòng đôi",price:130000,details:"Tối đa 25m²",status:"active"},{id:"hotel-family",name:"Khách sạn/Homestay • Phòng gia đình",price:190000,details:"Tối đa 50m²",status:"active"},{id:"hotel-dorm-under-8",name:"DORM dưới 8 giường",price:220000,details:"Tối đa 7 giường",status:"active"},{id:"hotel-dorm-8-plus",name:"DORM từ 8 giường",price:300000,details:"Từ 8 giường trở lên",status:"active"},{id:"apartment-1br",name:"1 phòng ngủ",price:250000,details:"Tối đa 50m²",status:"active"},{id:"apartment-2br",name:"2 phòng ngủ",price:350000,details:"Tối đa 70m²",status:"active"},{id:"apartment-3br",name:"3 phòng ngủ",price:450000,details:"Tối đa 100m²",status:"active"},{id:"villa-single",name:"Villa • Phòng đơn",price:100000,details:"Tối đa 15m²",status:"active"},{id:"villa-double",name:"Villa • Phòng đôi",price:140000,details:"Tối đa 25m²",status:"active"},{id:"villa-family",name:"Villa • Phòng gia đình",price:200000,details:"Tối đa 50m²",status:"active"}]},
  {id:"professional",name:"Vệ sinh chuyên nghiệp",description:"Nhà lâu năm, sau xây dựng và văn phòng.",longDescription:professionalCleaningLongDescription,benefits:professionalCleaningBenefits,status:"active",process:professionalInfo.process,tools:professionalInfo.tools.map(({name,description})=>({name,description})),plans:[
    {id:"p1",name:"Nhà lâu năm dưới 60m²",price:2100000,details:"Đã gồm dụng cụ & hóa chất",status:"active"},{id:"p2",name:"Nhà lâu năm 60–80m²",price:2700000,details:"Đã gồm dụng cụ & hóa chất",status:"active"},{id:"p3",name:"Nhà lâu năm 81–100m²",price:3300000,details:"Đã gồm dụng cụ & hóa chất",status:"active"}]},
  ...utilityServices.filter((service)=>!service.available).map((service)=>({id:service.slug,name:service.name,description:service.description,status:"active" as const,plans:[]})),
];

function useStoredState<T>(key:string, initial:T) {
  const [value,setValue]=useState(initial);
  useEffect(()=>{ try { const saved=localStorage.getItem(key); if(saved) setValue(JSON.parse(saved) as T); } catch {} },[key]);
  useEffect(()=>{ try { localStorage.setItem(key,JSON.stringify(value)); } catch {} },[key,value]);
  return [value,setValue] as const;
}
const money=(value:number)=>new Intl.NumberFormat("vi-VN").format(value)+"đ";

export function AdminConsole() {
  const {admin,logout}=useAdminAuth(); const router=useRouter();
  const [section,setSection]=useState<Section>("dashboard"); const [sidebar,setSidebar]=useState(false); const [query,setQuery]=useState(""); const [editor,setEditor]=useState<Editor>(null);
  const [customers,setCustomers]=useStoredState("everycare_admin_customers",initialCustomers);
  const [partners,setPartners]=useStoredState("everycare_admin_partners",initialPartners);
  const [groups,setGroups]=useStoredState("everycare_admin_services_v2",initialGroups);
  useEffect(()=>{setGroups(items=>{const updated=items.filter(item=>item.id!=="don-dep-van-phong-dinh-ky").map(item=>item.id==="room"?{...item,name:"Dọn dẹp nhà cửa",longDescription:item.longDescription||roomServiceLongDescription,benefits:item.benefits?.length?item.benefits:roomServiceBenefits}:item.id==="deep"?{...item,description:item.description==="Làm sạch toàn diện theo quy mô công việc."?"Làm sạch chuyên sâu toàn bộ không gian với đội nhóm 2–4 Tasker.":item.description,longDescription:item.longDescription||deepCleaningLongDescription,benefits:item.benefits?.length?item.benefits:deepCleaningBenefits}:item.id==="professional"?{...item,longDescription:item.longDescription||professionalCleaningLongDescription,benefits:item.benefits?.length?item.benefits:professionalCleaningBenefits}:item);const additions=["office","hospitality"].filter(id=>!updated.some(item=>item.id===id)).map(id=>initialGroups.find(item=>item.id===id)!);return [...updated,...additions]})},[setGroups]);
  const filteredCustomers=useMemo(()=>customers.filter(item=>(item.name+item.phone+item.email).toLowerCase().includes(query.toLowerCase())),[customers,query]);
  const filteredPartners=useMemo(()=>partners.filter(item=>(item.name+item.phone+item.services).toLowerCase().includes(query.toLowerCase())),[partners,query]);
  function navigate(next:Section){setSection(next);setQuery("");setSidebar(false)}
  function removeCustomer(id:string){if(confirm("Xóa khách hàng này khỏi danh sách?"))setCustomers(items=>items.filter(item=>item.id!==id))}
  function removePartner(id:string){if(confirm("Xóa cộng tác viên này khỏi danh sách?"))setPartners(items=>items.filter(item=>item.id!==id))}
  function removeGroup(id:string){if(confirm("Xóa nhóm dịch vụ và toàn bộ gói bên trong?"))setGroups(items=>items.filter(item=>item.id!==id))}
  function removePlan(groupId:string,id:string){if(confirm("Xóa gói dịch vụ này?"))setGroups(items=>items.map(group=>group.id===groupId?{...group,plans:group.plans.filter(plan=>plan.id!==id)}:group))}
  function toggleCustomer(id:string){setCustomers(items=>items.map(item=>item.id===id?{...item,status:item.status==="active"?"locked":"active"}:item))}
  function togglePartner(id:string){setPartners(items=>items.map(item=>item.id===id?{...item,status:item.status==="active"?"locked":"active"}:item))}
  function toggleGroup(id:string){setGroups(items=>items.map(item=>item.id===id?{...item,status:item.status==="active"?"locked":"active"}:item))}
  function saveEditor(data:Record<string,string|number>) {
    const id=editor?.item?.id ?? crypto.randomUUID();
    if(editor?.kind==="customer"){const item:Customer={id,name:String(data.name),phone:String(data.phone),email:String(data.email),orders:Number(data.orders||0),status:(data.status as Status)||"active",joined:String(data.joined||new Date().toLocaleDateString("vi-VN"))};setCustomers(items=>editor.item?items.map(x=>x.id===id?item:x):[item,...items]);}
    if(editor?.kind==="partner"){const item:Partner={id,name:String(data.name),phone:String(data.phone),kind:data.kind as Partner["kind"],services:String(data.services),members:Number(data.members||1),status:(data.status as Partner["status"])||"pending"};setPartners(items=>editor.item?items.map(x=>x.id===id?item:x):[item,...items]);}
    if(editor?.kind==="group"){const existing=editor.item as ServiceGroup|undefined;const process=String(data.process||"").split("\n").map(x=>x.trim()).filter(Boolean);const tools=String(data.tools||"").split("\n").map(line=>{const [name,...rest]=line.split("|");return{name:name.trim(),description:rest.join("|").trim()}}).filter(x=>x.name);const benefits=String(data.benefits||"").split("\n").map(line=>{const [title,...rest]=line.split("|");return{title:title.trim(),description:rest.join("|").trim()}}).filter(x=>x.title||x.description);const item:ServiceGroup={id,name:String(data.name),description:String(data.description),longDescription:String(data.longDescription||""),benefits,status:(data.status as Status)||"active",plans:existing?.plans??[],process,tools};setGroups(items=>editor.item?items.map(x=>x.id===id?item:x):[...items,item]);}
    if(editor?.kind==="plan"&&editor.groupId){const lines=(name:string)=>String(data[name]||"").split("\n").map(x=>x.trim()).filter(Boolean);const item:Plan={id,name:String(data.name),price:Number(data.price),details:String(data.details),status:(data.status as Status)||"active",workDetails:{overview:lines("overview"),scope:lines("scope"),livingRoom:lines("livingRoom"),bedroom:lines("bedroom"),kitchen:lines("kitchen"),bathroom:lines("bathroom")}};setGroups(items=>items.map(group=>group.id===editor.groupId?{...group,plans:editor.item?group.plans.map(x=>x.id===id?item:x):[...group.plans,item]}:group));}
    setEditor(null);
  }
  function signOut(){logout();router.replace("/dang-nhap")}

  return <main className="admin-v2"><aside className={sidebar?"admin-v2-side open":"admin-v2-side"}><div className="admin-v2-logo"><i><Sparkles/></i>Every<b>Care</b><button onClick={()=>setSidebar(false)}><X/></button></div><nav><small>TỔNG QUAN</small><button className={section==="dashboard"?"active":""} onClick={()=>navigate("dashboard")}><LayoutDashboard/>Bảng điều khiển</button><button className={section==="orders"?"active":""} onClick={()=>navigate("orders")}><ClipboardList/>Đơn hàng</button><small>QUẢN LÝ</small><button className={section==="services"?"active":""} onClick={()=>navigate("services")}><Boxes/>Nhóm & gói dịch vụ</button><button className={section==="partners"?"active":""} onClick={()=>navigate("partners")}><UserCheck/>Cộng tác viên</button><button className={section==="customers"?"active":""} onClick={()=>navigate("customers")}><Users/>Khách hàng</button><small>BÁO CÁO</small><button><BarChart3/>Doanh thu</button><button><Settings/>Cài đặt hệ thống</button></nav><div className="admin-v2-user"><span>LA</span><div><strong>{admin?.fullName}</strong><small>Quản trị viên cấp cao</small></div><button onClick={signOut} title="Đăng xuất"><LogOut/></button></div></aside>
    <section className="admin-v2-main"><header><button className="admin-v2-menu" onClick={()=>setSidebar(true)}><Menu/></button><div><strong>Hệ thống quản trị</strong><small>Vận hành dịch vụ EveryCare</small></div><button className="admin-notify"><Bell/><i>3</i></button><span className="admin-header-avatar">LA</span></header><div className="admin-v2-content">
      {section==="dashboard"&&<Dashboard customers={customers} partners={partners} groups={groups} onNavigate={navigate}/>} 
      {section==="orders"&&<OrdersManager/>}
      {section==="customers"&&<AdminCustomersManager/>}
      {section==="partners"&&<AdminPartnerApplications/>}
      {section==="services"&&<ServicesManager groups={groups} onAddGroup={()=>setEditor({kind:"group"})} onEditGroup={(item)=>setEditor({kind:"group",item})} onToggleGroup={toggleGroup} onDeleteGroup={removeGroup} onAddPlan={(groupId)=>setEditor({kind:"plan",groupId})} onEditPlan={(groupId,item)=>setEditor({kind:"plan",groupId,item})} onDeletePlan={removePlan}/>} 
    </div></section>{editor&&<AdminEditor editor={editor} onClose={()=>setEditor(null)} onSave={saveEditor}/>}</main>;
}

function Dashboard({customers,partners,groups,onNavigate}:{customers:Customer[];partners:Partner[];groups:ServiceGroup[];onNavigate:(section:Section)=>void}){
  return <><div className="admin-v2-title"><div><span>THỨ TƯ, 16 THÁNG 9</span><h1>Chào buổi sáng, Linh 👋</h1><p>Tổng quan hoạt động của EveryCare hôm nay.</p></div></div><div className="admin-v2-stats"><article><i className="green"><CircleDollarSign/></i><span><small>Doanh thu tháng</small><strong>128,4 triệu</strong><em>+12,5% so với tháng trước</em></span></article><article><i className="orange"><ClipboardList/></i><span><small>Đơn hôm nay</small><strong>24</strong><em>18 đơn đã có người nhận</em></span></article><article><i className="purple"><UserCheck/></i><span><small>Cộng tác viên</small><strong>{partners.length}</strong><em>{partners.filter(x=>x.status==="active").length} đang hoạt động</em></span></article><article><i className="blue"><Users/></i><span><small>Khách hàng</small><strong>{customers.length}</strong><em>{customers.filter(x=>x.status==="active").length} tài khoản hoạt động</em></span></article></div><div className="admin-quick-grid"><article><div><span className="admin-card-icon"><Boxes/></span><h2>Danh mục dịch vụ</h2><p>{groups.length} nhóm dịch vụ • {groups.reduce((sum,x)=>sum+x.plans.length,0)} gói đang cấu hình</p></div><button onClick={()=>onNavigate("services")}>Quản lý <ChevronRight/></button></article><article><div><span className="admin-card-icon"><UserCheck/></span><h2>Hồ sơ chờ duyệt</h2><p>{partners.filter(x=>x.status==="pending").length} cộng tác viên cần được kiểm tra hồ sơ</p></div><button onClick={()=>onNavigate("partners")}>Kiểm tra <ChevronRight/></button></article><article><div><span className="admin-card-icon"><ShieldCheck/></span><h2>Tài khoản bị khóa</h2><p>{customers.filter(x=>x.status==="locked").length+partners.filter(x=>x.status==="locked").length} tài khoản hiện không thể sử dụng hệ thống</p></div><button onClick={()=>onNavigate("customers")}>Xem ngay <ChevronRight/></button></article></div></>;
}
function PageHead({title,copy,button,onAdd}:{title:string;copy:string;button:string;onAdd:()=>void}){return <div className="admin-v2-title row"><div><h1>{title}</h1><p>{copy}</p></div><button className="admin-primary" onClick={onAdd}><Plus/>{button}</button></div>}
function SearchBox({value,onChange,placeholder}:{value:string;onChange:(value:string)=>void;placeholder:string}){return <div className="admin-toolbar"><div><Search/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div></div>}
function StatusBadge({status}:{status:Status|"pending"}){return <span className={`admin-status ${status}`}>{status==="active"?"Đang hoạt động":status==="locked"?"Đã khóa":"Chờ duyệt"}</span>}

type ApiBooking={id:string;code:string;customer:string;customerPhone:string;service:string;addressSnapshot:string;scheduledStartAt:string;status:string;cleaner:string|null;estimatedTotal:number;invitedPartners:number;createdAt:string;isRecurring:boolean;recurrenceRule:string|null;facilityName:string|null;contactName:string|null;contactPhone:string|null;accommodationType:string|null;customerRequest:string|null;extras:{description:string;amount:number}[]};
function recurringLabel(rule:string|null){if(!rule)return"";const values=Object.fromEntries(rule.split(";").map(part=>part.split("=")));const labels:Record<string,string>={MO:"Thứ 2",TU:"Thứ 3",WE:"Thứ 4",TH:"Thứ 5",FR:"Thứ 6",SA:"Thứ 7",SU:"Chủ nhật"};return `${String(values.BYDAY??"").split(",").map(day=>labels[day]??day).join(", ")} · ${values.TIME??""} · ${values.MONTHS??""} tháng`}
function OrdersManager(){
 const [orders,setOrders]=useState<ApiBooking[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const response=await fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL??"http://localhost:5185"}/api/admin/bookings`,{cache:"no-store"});if(!response.ok)throw new Error("Không thể tải đơn hàng.");setOrders(await response.json())}catch(reason){setError(reason instanceof TypeError?"Không thể kết nối API. Hãy kiểm tra backend và PostgreSQL.":reason instanceof Error?reason.message:"Không thể tải đơn hàng.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const statusLabel=(status:string)=>({Draft:"Chờ thanh toán cọc",Searching:"Chờ Tasker nhận",AwaitingCustomerSelection:"Chờ khách chọn",Assigned:"Đã có Tasker",PartnerTravelling:"Tasker đã đến",InProgress:"Đang thực hiện",AwaitingCustomerConfirmation:"Chờ khách xác nhận",IssueReported:"Đang hỗ trợ",Completed:"Hoàn thành",Cancelled:"Đã hủy",NoPartnerFound:"Đang mở rộng tìm kiếm"}[status]??status);
 const statusTone=(status:string)=>status==="Completed"?"green":status==="Cancelled"||status==="NoPartnerFound"||status==="IssueReported"?"orange":status==="InProgress"||status==="AwaitingCustomerConfirmation"?"purple":"blue";
 return <><div className="admin-v2-title row"><div><h1>Quản lý đơn hàng</h1><p>{orders.length} đơn được ghi nhận trong PostgreSQL</p></div><button className="admin-secondary" onClick={()=>void load()} disabled={loading}><RefreshCw className={loading?"spin":""}/>Làm mới</button></div>{error&&<div className="admin-api-error">{error}</div>}<div className="admin-data-card"><div className="admin-table-scroll"><table><thead><tr><th>MÃ ĐƠN</th><th>KHÁCH HÀNG</th><th>DỊCH VỤ</th><th>THỜI GIAN</th><th>CỘNG TÁC VIÊN</th><th>TRẠNG THÁI</th><th>TỔNG TIỀN</th></tr></thead><tbody>{orders.map(order=><tr key={order.id}><td><strong>{order.code}</strong><small>{new Date(order.createdAt).toLocaleString("vi-VN")}</small></td><td><strong>{order.customer}</strong><small>{order.customerPhone}</small>{order.contactName&&<small>Liên hệ: {order.contactName} • {order.contactPhone}</small>}</td><td><strong>{order.service}{order.isRecurring?" • Gói tháng":""}</strong>{order.facilityName&&<small>{order.facilityName} • {({hotel:"Khách sạn/Homestay",apartment:"Căn hộ dịch vụ",villa:"Villa/Nhà nguyên căn"} as Record<string,string>)[order.accommodationType??""]}</small>}<small>{order.addressSnapshot}</small>{order.extras?.map(extra=><small key={extra.description}>+ {extra.description}: {money(extra.amount)}</small>)}</td><td><strong>{order.isRecurring?recurringLabel(order.recurrenceRule):new Date(order.scheduledStartAt).toLocaleString("vi-VN")}</strong>{order.isRecurring&&<small>Bắt đầu {new Date(order.scheduledStartAt).toLocaleDateString("vi-VN")}</small>}</td><td><strong>{order.cleaner??"Đang tìm người"}</strong><small>Đã mời {order.invitedPartners} người/đội</small></td><td><span className={`status ${statusTone(order.status)}`}>{statusLabel(order.status)}</span></td><td><strong>{money(order.estimatedTotal)}</strong></td></tr>)}</tbody></table></div>{loading&&<div className="admin-empty"><LoaderCircle className="spin"/> Đang tải đơn hàng...</div>}{!loading&&!error&&orders.length===0&&<div className="admin-empty">Chưa có đơn hàng nào. Đơn khách xác nhận sẽ xuất hiện tại đây.</div>}</div></>;
}
function DataTable({type,rows,onEdit,onToggle,onDelete}:{type:"customer"|"partner";rows:(Customer|Partner)[];onEdit:(item:Customer|Partner)=>void;onToggle:(id:string)=>void;onDelete:(id:string)=>void}){return <div className="admin-data-card"><div className="admin-table-scroll"><table><thead><tr><th>{type==="customer"?"KHÁCH HÀNG":"CỘNG TÁC VIÊN"}</th><th>LIÊN HỆ</th><th>{type==="customer"?"ĐƠN HÀNG":"HÌNH THỨC"}</th><th>{type==="customer"?"NGÀY THAM GIA":"DỊCH VỤ"}</th><th>TRẠNG THÁI</th><th>THAO TÁC</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><div className="admin-person"><span>{row.name.split(" ").slice(-2).map(x=>x[0]).join("")}</span><div><strong>{row.name}</strong><small>{row.id}</small></div></div></td><td><strong>{row.phone}</strong><small>{"email" in row?row.email:""}</small></td><td>{"orders" in row?`${row.orders} đơn`:<><strong>{row.kind}</strong><small>{row.members} thành viên</small></>}</td><td>{"joined" in row?row.joined:row.services}</td><td><StatusBadge status={row.status}/></td><td><div className="admin-actions"><button title="Chỉnh sửa" onClick={()=>onEdit(row)}><Edit3/></button><button title={row.status==="locked"?"Mở khóa":"Khóa"} onClick={()=>onToggle(row.id)}>{row.status==="locked"?<Unlock/>:<Lock/>}</button><button className="danger" title="Xóa" onClick={()=>onDelete(row.id)}><Trash2/></button></div></td></tr>)}</tbody></table></div>{rows.length===0&&<div className="admin-empty">Không tìm thấy dữ liệu phù hợp.</div>}</div>}

function ServicesManager({groups,onAddGroup,onEditGroup,onToggleGroup,onDeleteGroup,onAddPlan,onEditPlan,onDeletePlan}:{groups:ServiceGroup[];onAddGroup:()=>void;onEditGroup:(item:ServiceGroup)=>void;onToggleGroup:(id:string)=>void;onDeleteGroup:(id:string)=>void;onAddPlan:(groupId:string)=>void;onEditPlan:(groupId:string,item:Plan)=>void;onDeletePlan:(groupId:string,id:string)=>void}){
 const [selected,setSelected]=useState(groups[0]?.id??""); useEffect(()=>{if(!groups.find(x=>x.id===selected))setSelected(groups[0]?.id??"")},[groups,selected]); const group=groups.find(x=>x.id===selected);
 return <><PageHead title="Nhóm và gói dịch vụ" copy="Thêm, sửa, khóa hoặc xóa các dịch vụ hiển thị cho khách hàng" button="Thêm nhóm dịch vụ" onAdd={onAddGroup}/><div className="service-admin-layout"><aside className="service-group-list">{groups.map(item=><button className={item.id===selected?"active":""} onClick={()=>setSelected(item.id)} key={item.id}><span><strong>{item.name}</strong><small>{item.plans.length} gói</small></span><StatusBadge status={item.status}/><ChevronRight/></button>)}{groups.length===0&&<p>Chưa có nhóm dịch vụ.</p>}</aside>{group&&<section className="service-detail"><div className="service-detail-head"><div><span className="admin-status active">NHÓM DỊCH VỤ</span><h2>{group.name}</h2><p>{group.description}</p></div><div className="admin-actions"><button title="Sửa nhóm" onClick={()=>onEditGroup(group)}><Edit3/></button><button title={group.status==="active"?"Khóa nhóm":"Mở khóa"} onClick={()=>onToggleGroup(group.id)}>{group.status==="active"?<Lock/>:<Unlock/>}</button><button className="danger" title="Xóa nhóm" onClick={()=>onDeleteGroup(group.id)}><Trash2/></button></div></div><div className="package-heading"><div><h3>Các gói trong nhóm</h3><p>Giá và mô tả sẽ hiển thị trên trang đặt lịch.</p></div><button className="admin-secondary" onClick={()=>onAddPlan(group.id)}><PackagePlus/>Thêm gói</button></div><div className="admin-package-grid">{group.plans.map(plan=><article key={plan.id}><div><StatusBadge status={plan.status}/><button><MoreHorizontal/></button></div><h3>{plan.name}</h3><p>{plan.details}</p><strong>{money(plan.price)}</strong><footer><button onClick={()=>onEditPlan(group.id,plan)}><Edit3/>Chỉnh sửa</button><button className="danger" onClick={()=>onDeletePlan(group.id,plan.id)}><Trash2/>Xóa</button></footer></article>)}{group.plans.length===0&&<div className="admin-empty">Nhóm này chưa có gói dịch vụ.</div>}</div></section>}</div></>;
}

function AdminEditor({editor,onClose,onSave}:{editor:NonNullable<Editor>;onClose:()=>void;onSave:(data:Record<string,string|number>)=>void}){
 const item=editor.item; const defaultDetails=editor.kind==="plan"?(item as Plan|undefined)?.workDetails??services.find(service=>service.id===editor.groupId)?.plans[0]?.workDetails:undefined; const groupItem=editor.kind==="group"?item as ServiceGroup|undefined:undefined; const baseItem=item as Customer|Partner|ServiceGroup|Plan|undefined; const [form,setForm]=useState<Record<string,string|number>>({name:baseItem?.name??"",phone:"phone" in (baseItem??{})?String((baseItem as Customer|Partner).phone):"",email:"email" in (baseItem??{})?String((baseItem as Customer).email):"",orders:"orders" in (baseItem??{})?Number((baseItem as Customer).orders):0,kind:"kind" in (baseItem??{})?String((baseItem as Partner).kind):"Cá nhân",services:"services" in (baseItem??{})?String((baseItem as Partner).services):"",members:"members" in (baseItem??{})?Number((baseItem as Partner).members):1,status:"status" in (baseItem??{})?String(baseItem?.status):"active",description:"description" in (baseItem??{})?String((baseItem as ServiceGroup).description):"",longDescription:groupItem?.longDescription??"",benefits:(groupItem?.benefits??[]).map(benefit=>`${benefit.title} | ${benefit.description}`).join("\n"),price:"price" in (baseItem??{})?Number((baseItem as Plan).price):0,details:"details" in (baseItem??{})?String((baseItem as Plan).details):"",overview:defaultDetails?.overview?.join("\n")??"",scope:defaultDetails?.scope?.join("\n")??"",livingRoom:defaultDetails?.livingRoom.join("\n")??"",bedroom:defaultDetails?.bedroom.join("\n")??"",kitchen:defaultDetails?.kitchen.join("\n")??"",bathroom:defaultDetails?.bathroom.join("\n")??"",process:(groupItem?.process??professionalInfo.process).join("\n"),tools:(groupItem?.tools??professionalInfo.tools).map(tool=>`${tool.name} | ${tool.description}`).join("\n")});
 const title=`${editor.item?"Chỉnh sửa":"Thêm"} ${editor.kind==="customer"?"khách hàng":editor.kind==="partner"?"cộng tác viên":editor.kind==="group"?"nhóm dịch vụ":"gói dịch vụ"}`;
 function field(name:string,value:string|number){setForm(current=>({...current,[name]:value}))} function submit(e:FormEvent){e.preventDefault();onSave(form)}
 return <div className="admin-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><form className="admin-modal" onSubmit={submit}><header><div><h2>{title}</h2><p>Cập nhật thông tin và lưu thay đổi.</p></div><button type="button" onClick={onClose}><X/></button></header><div className="admin-modal-fields">
  {(editor.kind==="customer"||editor.kind==="partner")&&<><label><span>Họ và tên</span><input required value={String(form.name??"")} onChange={e=>field("name",e.target.value)} placeholder="Nhập họ và tên"/></label><label><span>Số điện thoại</span><input required value={String(form.phone??"")} onChange={e=>field("phone",e.target.value)} placeholder="09xx xxx xxx"/></label></>}
  {editor.kind==="customer"&&<><label className="full"><span>Email</span><input type="email" value={String(form.email??"")} onChange={e=>field("email",e.target.value)} placeholder="email@example.com"/></label><label><span>Số đơn đã đặt</span><input type="number" min="0" value={String(form.orders??0)} onChange={e=>field("orders",Number(e.target.value))}/></label><StatusSelect value={String(form.status??"active")} onChange={value=>field("status",value)}/></>}
  {editor.kind==="partner"&&<><label><span>Hình thức</span><select value={String(form.kind??"Cá nhân")} onChange={e=>field("kind",e.target.value)}><option>Cá nhân</option><option>Đội nhóm</option></select></label><label><span>Số thành viên</span><input type="number" min="1" value={String(form.members??1)} onChange={e=>field("members",Number(e.target.value))}/></label><label className="full"><span>Dịch vụ đăng ký</span><input required value={String(form.services??"")} onChange={e=>field("services",e.target.value)} placeholder="Dọn dẹp nhà cửa, Tổng vệ sinh..."/></label><label><span>Trạng thái</span><select value={String(form.status??"pending")} onChange={e=>field("status",e.target.value)}><option value="pending">Chờ duyệt</option><option value="active">Đang hoạt động</option><option value="locked">Đã khóa</option></select></label></>}
  {editor.kind==="group"&&<><label className="full"><span>Tên nhóm dịch vụ</span><input required value={String(form.name??"")} onChange={e=>field("name",e.target.value)} placeholder="Ví dụ: Dọn dẹp nhà cửa"/></label><label className="full"><span>Mô tả ngắn</span><textarea required value={String(form.description??"")} onChange={e=>field("description",e.target.value)} placeholder="Mô tả ngắn hiển thị trên thẻ dịch vụ"/></label><label className="full"><span>Mô tả chi tiết trong cửa sổ dịch vụ</span><textarea value={String(form.longDescription??"")} onChange={e=>field("longDescription",e.target.value)} placeholder="Giới thiệu đầy đủ về dịch vụ và giá trị mang lại cho khách hàng"/></label><label className="full"><span>Lợi ích dịch vụ — Tiêu đề | Nội dung, mỗi dòng một mục</span><textarea value={String(form.benefits??"")} onChange={e=>field("benefits",e.target.value)} placeholder={"Tiết kiệm thời gian | Nội dung mô tả...\nGiá cả minh bạch | Nội dung mô tả..."}/></label><StatusSelect value={String(form.status??"active")} onChange={value=>field("status",value)}/><label className="full"><span>Quy trình vệ sinh chuyên nghiệp — mỗi dòng một bước</span><textarea value={String(form.process??"")} onChange={e=>field("process",e.target.value)} placeholder="Khảo sát hiện trạng&#10;Thu gom rác thô..."/></label><label className="full"><span>Dụng cụ & hóa chất — Tên | Mô tả, mỗi dòng một mục</span><textarea value={String(form.tools??"")} onChange={e=>field("tools",e.target.value)} placeholder="Máy hút bụi | Hút bụi mịn công suất cao"/></label></>}
  {editor.kind==="plan"&&<><label className="full"><span>Tên gói dịch vụ</span><input required value={String(form.name??"")} onChange={e=>field("name",e.target.value)} placeholder="Ví dụ: Gói 2 giờ"/></label><label><span>Giá gói</span><input required type="number" min="0" value={String(form.price??0)} onChange={e=>field("price",Number(e.target.value))}/></label><StatusSelect value={String(form.status??"active")} onChange={value=>field("status",value)}/><label className="full"><span>Diện tích, thời lượng, số người</span><textarea required value={String(form.details??"")} onChange={e=>field("details",e.target.value)} placeholder="Tối đa 55m² • 1 người • 2 giờ"/></label><label className="full"><span>Công việc tổng quát — mỗi dòng một việc</span><textarea value={String(form.overview??"")} onChange={e=>field("overview",e.target.value)}/></label><label className="full"><span>Phạm vi công việc — mỗi dòng một mục</span><textarea value={String(form.scope??"")} onChange={e=>field("scope",e.target.value)}/></label><label><span>Phòng khách</span><textarea value={String(form.livingRoom??"")} onChange={e=>field("livingRoom",e.target.value)}/></label><label><span>Phòng ngủ</span><textarea value={String(form.bedroom??"")} onChange={e=>field("bedroom",e.target.value)}/></label><label><span>Nhà bếp</span><textarea value={String(form.kitchen??"")} onChange={e=>field("kitchen",e.target.value)}/></label><label><span>Nhà vệ sinh</span><textarea value={String(form.bathroom??"")} onChange={e=>field("bathroom",e.target.value)}/></label></>}
 </div><footer><button type="button" className="admin-cancel" onClick={onClose}>Hủy</button><button className="admin-primary">Lưu thay đổi</button></footer></form></div>;
}
function StatusSelect({value,onChange}:{value:string;onChange:(value:string)=>void}){return <label><span>Trạng thái</span><select value={value} onChange={e=>onChange(e.target.value)}><option value="active">Đang hoạt động</option><option value="locked">Đã khóa</option></select></label>}
