"use client";

import Link from "next/link";
import { CalendarDays, Check, ChevronDown, ClipboardList, Heart, LoaderCircle, LogOut, MapPin, Phone, Star, Trash2, UserCheck } from "lucide-react";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { useAuth } from "@/features/auth/components/auth-provider";
import { SiteHeader } from "@/components/layout/site-header";

type Tasker={id:string;name:string;avatarUrl:string|null;averageRating:number;phone:string;isFavorite:boolean};
type Candidate={partnerId:string;name:string;avatarUrl:string|null;averageRating:number;completedBookings:number;distanceMetersAtInvitation:number|null};
type Booking={id:string;code:string;service:string;package:string|null;addressSnapshot:string;scheduledStartAt:string;status:string;estimatedTotal:number;customerRequest:string|null;completionReportedAt:string|null;issueNote:string|null;occurrenceNumber:number|null;contract:{id:string;code:string;status:string;contractMonths:number;totalOccurrences:number;completedOccurrences:number;estimatedTotal:number;depositAmount:number;remainingAmount:number}|null;candidates:Candidate[];tasker:Tasker|null;review:{rating:number;comment:string|null;createdAt:string}|null;payment:{status:string;amount:number;depositAmount:number;remainingAmount:number;refundedAmount:number;platformFee:number;taskerNetAmount:number}|null};
type Favorite={partnerId:string;name:string;avatarUrl:string|null;averageRating:number;completedBookings:number;partnerType:"Individual"|"Team";isAvailable:boolean;services:string[];favoritedAt:string};

const API=process.env.NEXT_PUBLIC_API_BASE_URL??"http://localhost:5185";
const money=(value:number)=>new Intl.NumberFormat("vi-VN").format(value)+"đ";
const avatarText=(name:string)=>name.split(" ").filter(Boolean).slice(-2).map(part=>part[0]).join("").toUpperCase();
const statusLabel:Record<string,string>={Draft:"Chờ thanh toán cọc",Searching:"Chờ Tasker nhận",AwaitingCustomerSelection:"Chờ chọn Tasker",Assigned:"Đã có Tasker",PartnerTravelling:"Tasker đã đến",InProgress:"Đang thực hiện",AwaitingCustomerConfirmation:"Chờ khách xác nhận",IssueReported:"Đang hỗ trợ",Completed:"Hoàn thành",Cancelled:"Đã hủy",NoPartnerFound:"Đang mở rộng tìm kiếm"};

export default function AccountPage(){
 const {customer,isLoading,logout}=useAuth();const router=useRouter();
 const [bookings,setBookings]=useState<Booking[]>([]);const [favorites,setFavorites]=useState<Favorite[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");const [actionId,setActionId]=useState("");const [showOrders,setShowOrders]=useState(false);
 const load=useCallback(async()=>{if(!customer)return;setLoading(true);try{const [bookingResponse,favoriteResponse]=await Promise.all([fetch(`${API}/api/customer-bookings?phone=${encodeURIComponent(customer.phone)}`,{cache:"no-store"}),fetch(`${API}/api/customer-favorites?phone=${encodeURIComponent(customer.phone)}`,{cache:"no-store"})]);if(bookingResponse.ok)setBookings(await bookingResponse.json());if(favoriteResponse.ok)setFavorites(await favoriteResponse.json())}finally{setLoading(false)}},[customer]);
 useEffect(()=>{if(!isLoading&&!customer)router.replace("/dang-nhap?returnUrl=%2Ftai-khoan");else if(customer)void load()},[customer,isLoading,router,load]);
 async function bookingAction(id:string,action:"confirm-completion"|"report-issue"|"cancel"){if(!customer)return;let note:string|undefined;if(action==="report-issue"){note=window.prompt("Vui lòng mô tả vấn đề cần hỗ trợ:")??undefined;if(!note)return}if(action==="cancel"&&!confirm("Bạn chắc chắn muốn hủy? Mức hoàn tiền phụ thuộc thời gian còn lại trước lịch làm."))return;setActionId(id+action);setMessage("");try{const response=await fetch(`${API}/api/customer-bookings/${id}/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone:customer.phone,note})});const data=await response.json();if(!response.ok)throw new Error(data.message);setMessage(data.message);await load()}catch(error){setMessage(error instanceof Error?error.message:"Không thể cập nhật đơn.")}finally{setActionId("")}}
 async function toggleFavorite(partnerId:string,isFavorite:boolean){if(!customer)return;setActionId(partnerId+"favorite");setMessage("");try{const response=await fetch(`${API}/api/customer-favorites/${partnerId}${isFavorite?`?phone=${encodeURIComponent(customer.phone)}`:""}`,{method:isFavorite?"DELETE":"POST",headers:isFavorite?undefined:{"Content-Type":"application/json"},body:isFavorite?undefined:JSON.stringify({phone:customer.phone})});const data=await response.json();if(!response.ok)throw new Error(data.message);setMessage(data.message);await load()}catch(error){setMessage(error instanceof Error?error.message:"Không thể cập nhật Tasker yêu thích.")}finally{setActionId("")}}
 async function selectPartner(bookingId:string,partnerId:string){if(!customer)return;setActionId(bookingId+partnerId);setMessage("");try{const response=await fetch(`${API}/api/customer-bookings/${bookingId}/select-partner`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone:customer.phone,partnerProfileId:partnerId})});const data=await response.json();if(!response.ok)throw new Error(data.message);setMessage(data.message);await load()}catch(error){setMessage(error instanceof Error?error.message:"Không thể chọn Tasker.")}finally{setActionId("")}}
 async function submitReview(bookingId:string,rating:number,comment:string){if(!customer)return;setActionId(bookingId+"review");setMessage("");try{const response=await fetch(`${API}/api/customer-bookings/${bookingId}/review`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone:customer.phone,rating,comment})});const data=await response.json();if(!response.ok)throw new Error(data.message);setMessage(data.message);await load()}catch(error){setMessage(error instanceof Error?error.message:"Không thể gửi đánh giá.")}finally{setActionId("")}}
 if(!customer)return <main className="subpage"><SiteHeader/><div className="auth-gate-loading"><p>Đang tải tài khoản...</p></div></main>;
 const activeOrders=bookings.filter(item=>!["Completed","Cancelled"].includes(item.status)).length;
 return <main className="subpage account-page"><SiteHeader/><div className="shell account-layout">
  <aside className="profile-card"><span className="profile-avatar">{avatarText(customer.fullName)}</span><h1>{customer.fullName}</h1><p><Phone/> {customer.phone}</p><span className="verified-customer">Tài khoản khách hàng</span><button onClick={()=>{logout();router.push("/")}}><LogOut/> Đăng xuất</button></aside>
  <section className="account-main"><div className="account-welcome"><div><span className="eyebrow">Tài khoản của tôi</span><h2>Lịch dọn của tôi</h2><p>Theo dõi Tasker, tiến độ và thanh toán đơn hàng.</p></div><Link className="button" href="/dat-lich">Đặt lịch mới</Link></div>{message&&<div className="customer-booking-message">{message}</div>}
   <section className="favorite-taskers-section"><div className="favorite-taskers-heading"><div><span><Heart/></span><div><h3>Tasker yêu thích</h3><p>Những Tasker này sẽ được ưu tiên khi bạn đặt lịch lần sau.</p></div></div><b>{favorites.length}</b></div>{favorites.length>0?<div className="favorite-taskers-list">{favorites.map(tasker=><article key={tasker.partnerId}><span className="favorite-tasker-avatar">{tasker.avatarUrl?<img src={tasker.avatarUrl} alt={tasker.name}/>:avatarText(tasker.name)}</span><div><strong>{tasker.name}</strong><small><Star/> {tasker.averageRating.toFixed(1)} · {tasker.completedBookings} công việc</small><p>{tasker.services.slice(0,2).join(" · ")||"Tasker EveryCare"}</p></div><span className={tasker.isAvailable?"favorite-available online":"favorite-available"}>{tasker.isAvailable?"Đang nhận việc":"Tạm nghỉ"}</span><button title="Xóa khỏi yêu thích" disabled={actionId===tasker.partnerId+"favorite"} onClick={()=>void toggleFavorite(tasker.partnerId,true)}>{actionId===tasker.partnerId+"favorite"?<LoaderCircle className="spin"/>:<Trash2/>}</button></article>)}</div>:<div className="favorite-taskers-empty"><Heart/><span><strong>Chưa có Tasker yêu thích</strong><small>Sau khi công việc hoàn thành, bạn có thể lưu Tasker để ưu tiên cho lần đặt tiếp theo.</small></span></div>}</section>
   <section className={showOrders?"orders-accordion open":"orders-accordion"}><button className="orders-accordion-toggle" onClick={()=>setShowOrders(value=>!value)} aria-expanded={showOrders}><span className="orders-accordion-icon"><ClipboardList/></span><span className="orders-accordion-copy"><strong>Đơn hàng của tôi</strong><small>{loading?"Đang cập nhật danh sách...":bookings.length?`${bookings.length} lượt đã đặt · ${activeOrders} lượt đang hoạt động`:"Bạn chưa có đơn hàng nào"}</small></span>{activeOrders>0&&<b>{activeOrders} đang xử lý</b>}<ChevronDown className="orders-accordion-chevron"/></button>{showOrders&&(loading?<div className="customer-booking-loading"><LoaderCircle className="spin"/> Đang tải đơn hàng...</div>:<div className="customer-booking-list">{bookings.map(item=><BookingCard key={item.id} item={item} actionId={actionId} onAction={bookingAction} onFavorite={toggleFavorite} onSelectPartner={selectPartner} onReview={submitReview}/>)}{bookings.length===0&&<div className="customer-booking-empty">Bạn chưa có đơn hàng nào.</div>}</div>)}</section>
  </section>
 </div></main>
}

function BookingCard({item,actionId,onAction,onFavorite,onSelectPartner,onReview}:{item:Booking;actionId:string;onAction:(id:string,action:"confirm-completion"|"report-issue"|"cancel")=>Promise<void>;onFavorite:(partnerId:string,isFavorite:boolean)=>Promise<void>;onSelectPartner:(bookingId:string,partnerId:string)=>Promise<void>;onReview:(bookingId:string,rating:number,comment:string)=>Promise<void>}){
 const [rating,setRating]=useState(5);const [comment,setComment]=useState("");
 return <article className="customer-booking-card"><header><div><small>{item.contract?`${item.contract.code} · Lượt ${item.occurrenceNumber}/${item.contract.totalOccurrences}`:item.code}</small><h3>{item.service}{item.package?` • ${item.package}`:""}</h3>{item.contract&&<p className="contract-progress">Hợp đồng {item.contract.contractMonths} tháng · Đã hoàn thành {item.contract.completedOccurrences}/{item.contract.totalOccurrences} lượt</p>}</div><span className={`customer-booking-status ${item.status.toLowerCase()}`}>{statusLabel[item.status]??item.status}</span></header><div className="customer-booking-meta"><p><CalendarDays/>{new Date(item.scheduledStartAt).toLocaleString("vi-VN")}</p><p><MapPin/>{item.addressSnapshot}</p></div>
 {item.status==="AwaitingCustomerSelection"&&<section className="tasker-candidate-section"><h4><UserCheck/> Chọn Tasker đã đồng ý nhận lịch</h4>{item.candidates.length?item.candidates.map(candidate=><div className="tasker-candidate" key={candidate.partnerId}><span>{candidate.avatarUrl?<img src={candidate.avatarUrl} alt={candidate.name}/>:avatarText(candidate.name)}</span><div><strong>{candidate.name}</strong><small><Star/> {candidate.averageRating.toFixed(1)} · {candidate.completedBookings} công việc{candidate.distanceMetersAtInvitation?` · ${(candidate.distanceMetersAtInvitation/1000).toFixed(1)} km`:""}</small></div><button className="button" disabled={actionId===item.id+candidate.partnerId} onClick={()=>void onSelectPartner(item.id,candidate.partnerId)}>{actionId===item.id+candidate.partnerId?<LoaderCircle className="spin"/>:"Chọn Tasker"}</button></div>):<p>Đang chờ Tasker phù hợp đồng ý nhận lịch.</p>}</section>}
 {item.tasker&&<div className="assigned-tasker"><span>{item.tasker.avatarUrl?<img src={item.tasker.avatarUrl} alt={item.tasker.name}/>:avatarText(item.tasker.name)}</span><div><small>Tasker phụ trách</small><strong>{item.tasker.name}</strong><p><Star/> {item.tasker.averageRating.toFixed(1)} • {item.tasker.phone}</p></div><b>Hẹn {new Date(item.scheduledStartAt).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"})}</b></div>}
 <div className="booking-payment-row"><span><small>Giá trị lượt</small><strong>{money(item.estimatedTotal)}</strong></span><span><small>Đã cọc</small><strong>{money(item.payment?.depositAmount??0)}</strong></span><span><small>Còn lại</small><strong>{money(item.payment?.remainingAmount??0)}</strong></span></div>{item.status==="AwaitingCustomerConfirmation"&&<div className="completion-alert"><Check/><span><strong>Tasker báo đã hoàn thành</strong><small>Vui lòng xác nhận hoặc báo vấn đề. Sau 24 giờ lượt này sẽ tự hoàn thành.</small></span></div>}
 {item.status==="Completed"&&item.tasker&&!item.review&&<form className="booking-review" onSubmit={event=>{event.preventDefault();void onReview(item.id,rating,comment)}}><strong>Đánh giá Tasker cho lượt làm việc này</strong><div>{[1,2,3,4,5].map(value=><button type="button" className={value<=rating?"active":""} onClick={()=>setRating(value)} key={value} aria-label={`${value} sao`}><Star/></button>)}</div><textarea maxLength={500} value={comment} onChange={event=>setComment(event.target.value)} placeholder="Nhận xét về chất lượng phục vụ (không bắt buộc)"/><button className="button" disabled={actionId===item.id+"review"}>{actionId===item.id+"review"?<LoaderCircle className="spin"/>:"Gửi đánh giá"}</button></form>}
 {item.review&&<div className="submitted-review"><span>{Array.from({length:5},(_,index)=><Star key={index} className={index<item.review!.rating?"active":""}/>)}</span><strong>Đánh giá của bạn: {item.review.rating}/5</strong>{item.review.comment&&<p>{item.review.comment}</p>}</div>}
 <footer>{item.status==="AwaitingCustomerConfirmation"&&<><button onClick={()=>void onAction(item.id,"report-issue")}>Cần hỗ trợ / Báo vấn đề</button><button className="button" disabled={actionId===item.id+"confirm-completion"} onClick={()=>void onAction(item.id,"confirm-completion")}>Xác nhận hoàn thành</button></>}{item.status==="Completed"&&item.tasker&&<button className={item.tasker.isFavorite?"favorite-booking-button selected":"favorite-booking-button"} disabled={actionId===item.tasker.id+"favorite"} onClick={()=>void onFavorite(item.tasker!.id,item.tasker!.isFavorite)}><Heart/>{item.tasker.isFavorite?"Đã yêu thích":"Thêm vào Tasker yêu thích"}</button>}{["Draft","Searching","AwaitingCustomerSelection","Assigned"].includes(item.status)&&<button className="cancel-customer-booking" disabled={actionId===item.id+"cancel"} onClick={()=>void onAction(item.id,"cancel")}>{item.contract?"Hủy hợp đồng":"Hủy lịch"}</button>}</footer></article>
}
