"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Bell, BriefcaseBusiness, CalendarDays, Check, Clock3, Home, LoaderCircle, LogOut, MapPin, Plus, RefreshCw, Save, Settings2, X, XCircle } from "lucide-react";
import { API_BASE, partnerHeaders, PARTNER_TOKEN_KEY } from "@/lib/partner-auth";

type Profile={fullName:string;phone:string;email:string;partnerType:"Individual"|"Team";teamName?:string;teamSize:number;isAvailable:boolean;serviceAddress:string;averageRating:number;completedBookings:number;walletBalance:number;services:string[]};
type Rule={dayOfWeek:string;startTime:string;endTime:string;isActive:boolean};type Override={date:string;isUnavailable:boolean;startTime:string|null;endTime:string|null;note?:string};
type Scheduled={id:string;code:string;addressSnapshot:string;scheduledStartAt:string;scheduledEndAt:string;status:string;customerRequest:string|null;taskerConfirmedAt:string|null;arrivedAt:string|null;startedAt:string|null;completionReportedAt:string|null};
type Invitation={id:string;status:string;invitedAt:string;expiresAt:string;distanceMetersAtInvitation:number|null;code:string;service:string;addressSnapshot:string;scheduledStartAt:string;scheduledEndAt:string;requiredWorkers:number;estimatedTotal:number;bookingStatus:string;customerRequest:string|null};
type Notification={id:string;title:string;message:string;isRead:boolean;createdAt:string};
const days=[{value:"Monday",label:"Thứ Hai"},{value:"Tuesday",label:"Thứ Ba"},{value:"Wednesday",label:"Thứ Tư"},{value:"Thursday",label:"Thứ Năm"},{value:"Friday",label:"Thứ Sáu"},{value:"Saturday",label:"Thứ Bảy"},{value:"Sunday",label:"Chủ Nhật"}];
const money=(n:number)=>new Intl.NumberFormat("vi-VN").format(n)+"đ";

export default function PartnerPortal(){
 const router=useRouter();const [tab,setTab]=useState<"home"|"schedule"|"jobs"|"notifications">("home");const [profile,setProfile]=useState<Profile|null>(null);const [rules,setRules]=useState<Rule[]>([]);const [overrides,setOverrides]=useState<Override[]>([]);const [bookings,setBookings]=useState<Scheduled[]>([]);const [invitations,setInvitations]=useState<Invitation[]>([]);const [notifications,setNotifications]=useState<Notification[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
 const request=useCallback(async(path:string,options?:RequestInit)=>{const response=await fetch(`${API_BASE}${path}`,{...options,headers:{...partnerHeaders(),...(options?.body?{"Content-Type":"application/json"}:{})}});if(response.status===401){localStorage.removeItem(PARTNER_TOKEN_KEY);router.replace("/dang-nhap");throw new Error("Phiên đăng nhập đã hết hạn.")}const data=response.status===204?{}:await response.json();if(!response.ok){const validation=data.errors?Object.values(data.errors).flat().join(" "):null;throw new Error(data.message??validation??"Không thể xử lý yêu cầu.")}return data},[router]);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [me,calendar,jobs,alerts]=await Promise.all([request("/api/partner/me"),request("/api/partner/me/availability"),request("/api/partner/me/invitations"),request("/api/partner/me/notifications")]);setProfile(me);setRules(calendar.rules.map((x:Rule)=>({...x,startTime:x.startTime.slice(0,5),endTime:x.endTime.slice(0,5)})));setOverrides(calendar.overrides.map((x:Override)=>({...x,startTime:x.startTime?.slice(0,5)??null,endTime:x.endTime?.slice(0,5)??null})));setBookings(calendar.bookings);setInvitations(jobs);setNotifications(alerts)}catch(reason){setError(reason instanceof TypeError?"Không thể kết nối backend.":reason instanceof Error?reason.message:"Không thể tải dữ liệu.")}finally{setLoading(false)}},[request]);
 useEffect(()=>{if(!localStorage.getItem(PARTNER_TOKEN_KEY)){router.replace("/dang-nhap");return}void load()},[load,router]);
 const pending=useMemo(()=>invitations.filter(x=>x.status==="Invited"&&new Date(x.expiresAt)>new Date()),[invitations]);
 function ruleFor(day:string){return rules.find(x=>x.dayOfWeek===day)}
 function toggleDay(day:string){const existing=ruleFor(day);setRules(current=>existing?current.filter(x=>x.dayOfWeek!==day):[...current,{dayOfWeek:day,startTime:"08:00",endTime:"17:00",isActive:true}])}
 function updateRule(day:string,key:"startTime"|"endTime",value:string){setRules(current=>current.map(x=>x.dayOfWeek===day?{...x,[key]:value}:x))}
 function addOverride(){setOverrides(current=>[...current,{date:new Date(Date.now()+86400000).toISOString().slice(0,10),isUnavailable:true,startTime:null,endTime:null,note:""}])}
 async function saveSchedule(){setSaving(true);setError("");setMessage("");const withSeconds=(value:string|null)=>value&&value.length===5?`${value}:00`:value;try{const data=await request("/api/partner/me/availability",{method:"PUT",body:JSON.stringify({rules:rules.map(x=>({...x,startTime:withSeconds(x.startTime),endTime:withSeconds(x.endTime)})),overrides:overrides.map(x=>({...x,startTime:withSeconds(x.startTime),endTime:withSeconds(x.endTime)}))})});setMessage(data.message);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Không thể lưu lịch.")}finally{setSaving(false)}}
 async function toggleAvailable(){if(!profile)return;try{const data=await request("/api/partner/me/job-invitations",{method:"PATCH",body:JSON.stringify({enabled:!profile.isAvailable})});setProfile({...profile,isAvailable:data.isAvailable});setMessage(data.message);if(data.invitationsCreated>0)await load()}catch(reason){setError(reason instanceof Error?reason.message:"Không thể cập nhật.")}}
 async function respond(id:string,accept:boolean){setSaving(true);try{const data=await request(`/api/partner/me/invitations/${id}/respond`,{method:"POST",body:JSON.stringify({accept})});setMessage(data.message);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Không thể phản hồi.")}finally{setSaving(false)}}
 async function cancelBooking(id:string){if(!confirm("Bạn chắc chắn muốn hủy nhận đơn này? Hệ thống sẽ tìm người thay thế ngay."))return;setSaving(true);try{const data=await request(`/api/partner/me/bookings/${id}/cancel`,{method:"POST",body:JSON.stringify({reason:"Đối tác không thể tiếp tục thực hiện lịch đã nhận."})});setMessage(data.message);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Không thể hủy nhận việc.")}finally{setSaving(false)}}
 async function advanceBooking(id:string,action:"confirm"|"arrive"|"start"|"complete"){setSaving(true);try{const data=await request(`/api/partner/me/bookings/${id}/${action}`,{method:"POST"});setMessage(data.message);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Không thể cập nhật trạng thái.")}finally{setSaving(false)}}
 async function logout(){try{await request("/api/partner/auth/logout",{method:"POST"})}catch{}localStorage.removeItem(PARTNER_TOKEN_KEY);router.replace("/dang-nhap")}
 if(loading&&!profile)return <main className="partner-portal-loading"><LoaderCircle className="spin"/>Đang tải trang đối tác...</main>;
 return <main className="partner-portal"><aside><div className="portal-brand"><BriefcaseBusiness/>Every<b>Care</b></div><nav><button className={tab==="home"?"active":""} onClick={()=>setTab("home")}><Home/>Tổng quan</button><button className={tab==="schedule"?"active":""} onClick={()=>setTab("schedule")}><CalendarDays/>Lịch làm việc</button><button className={tab==="jobs"?"active":""} onClick={()=>setTab("jobs")}><BriefcaseBusiness/>Việc phù hợp {pending.length>0&&<i>{pending.length}</i>}</button><button className={tab==="notifications"?"active":""} onClick={()=>setTab("notifications")}><Bell/>Thông báo</button></nav><button className="portal-logout" onClick={()=>void logout()}><LogOut/>Đăng xuất</button></aside><section className="portal-main"><header><div><small>KHU VỰC ĐỐI TÁC</small><strong>{profile?.teamName||profile?.fullName}</strong></div><button onClick={()=>void load()}><RefreshCw className={loading?"spin":""}/></button></header><div className="portal-content">{error&&<div className="portal-alert error">{error}<button onClick={()=>setError("")}><X/></button></div>}{message&&<div className="portal-alert success"><Check/>{message}<button onClick={()=>setMessage("")}><X/></button></div>}
  {tab==="home"&&profile&&<><div className="portal-title"><span>Tổng quan</span><h1>Chào {profile.fullName}</h1><p>Bạn không cần luôn trực tuyến. Hệ thống lưu lời mời dựa trên lịch rảnh đã đăng ký.</p></div><div className="portal-stats"><article><BriefcaseBusiness/><span><small>Lời mời còn hiệu lực</small><strong>{pending.length}</strong></span></article><article><CalendarDays/><span><small>Đơn đang thực hiện</small><strong>{bookings.length}</strong></span></article><article><Settings2/><span><small>Ví Tasker</small><strong>{money(profile.walletBalance)}</strong></span></article></div><section className="availability-toggle"><div><span className={profile.isAvailable?"online":"offline"}/><div><h2>Nhận lời mời công việc mới</h2><p>{profile.isAvailable?"Đang bật — lời mời vẫn được lưu khi bạn đóng website.":"Đang tắt — các đơn đã nhận không bị hủy."}</p></div></div><button className={profile.isAvailable?"toggle on":"toggle"} onClick={()=>void toggleAvailable()}><i/></button></section><section className="portal-card"><h2>Lịch đã nhận và tiến độ công việc</h2>{bookings.length?bookings.map(item=><div className="scheduled-job lifecycle-job" key={item.id}><CalendarDays/><span><strong>{item.code} • {new Date(item.scheduledStartAt).toLocaleString("vi-VN")}</strong><small>{item.addressSnapshot}</small>{item.customerRequest&&<small>Yêu cầu: {item.customerRequest}</small>}</span><b>{item.status==="Assigned"?item.taskerConfirmedAt?"Đã xác nhận lịch":"Cần xác nhận":"PartnerTravelling"===item.status?"Tasker đã đến":item.status==="InProgress"?"Đang thực hiện":"Chờ khách xác nhận"}</b><div className="job-actions">{item.status==="Assigned"&&!item.taskerConfirmedAt&&<button onClick={()=>void advanceBooking(item.id,"confirm")}>Xác nhận lịch</button>}{item.status==="Assigned"&&item.taskerConfirmedAt&&<button onClick={()=>void advanceBooking(item.id,"arrive")}>Tasker đã đến</button>}{item.status==="PartnerTravelling"&&<button onClick={()=>void advanceBooking(item.id,"start")}>Bắt đầu làm</button>}{item.status==="InProgress"&&<button onClick={()=>void advanceBooking(item.id,"complete")}>Báo hoàn thành</button>}{(item.status==="Assigned"||item.status==="PartnerTravelling")&&<button className="cancel-job" disabled={saving} onClick={()=>void cancelBooking(item.id)}>Hủy nhận</button>}</div></div>):<div className="portal-empty">Chưa có đơn nào được phân công.</div>}</section></>}
  {tab==="schedule"&&<><div className="portal-title"><span>Lịch làm việc</span><h1>Đăng ký thời gian rảnh</h1><p>Khung giờ phải bao phủ toàn bộ thời lượng công việc. Hệ thống tự chừa 1 giờ di chuyển giữa hai đơn.</p></div><section className="portal-card schedule-editor"><h2>Lịch lặp lại hằng tuần</h2>{days.map(day=>{const rule=ruleFor(day.value);return <div className="weekday-row" key={day.value}><label><input type="checkbox" checked={!!rule} onChange={()=>toggleDay(day.value)}/><strong>{day.label}</strong></label>{rule?<div><input type="time" value={rule.startTime} onChange={e=>updateRule(day.value,"startTime",e.target.value)}/><span>đến</span><input type="time" value={rule.endTime} onChange={e=>updateRule(day.value,"endTime",e.target.value)}/></div>:<small>Không làm việc</small>}</div>})}</section><section className="portal-card override-editor"><div className="card-heading"><div><h2>Ngày nghỉ hoặc giờ đặc biệt</h2><p>Thiết lập này sẽ thay thế lịch tuần ở đúng ngày đã chọn.</p></div><button onClick={addOverride}><Plus/>Thêm ngày</button></div>{overrides.map((item,index)=><div className="override-row" key={index}><input type="date" value={item.date} onChange={e=>setOverrides(current=>current.map((x,i)=>i===index?{...x,date:e.target.value}:x))}/><label><input type="checkbox" checked={item.isUnavailable} onChange={e=>setOverrides(current=>current.map((x,i)=>i===index?{...x,isUnavailable:e.target.checked,startTime:e.target.checked?null:"08:00",endTime:e.target.checked?null:"17:00"}:x))}/>Nghỉ cả ngày</label>{!item.isUnavailable&&<><input type="time" value={item.startTime??"08:00"} onChange={e=>setOverrides(current=>current.map((x,i)=>i===index?{...x,startTime:e.target.value}:x))}/><span>—</span><input type="time" value={item.endTime??"17:00"} onChange={e=>setOverrides(current=>current.map((x,i)=>i===index?{...x,endTime:e.target.value}:x))}/></>}<button onClick={()=>setOverrides(current=>current.filter((_,i)=>i!==index))}><XCircle/></button></div>)}</section><button className="button portal-save" disabled={saving} onClick={()=>void saveSchedule()}>{saving?<LoaderCircle className="spin"/>:<Save/>}Lưu lịch làm việc</button></>}
  {tab==="jobs"&&<><div className="portal-title"><span>Việc phù hợp</span><h1>Lời mời công việc</h1><p>Chỉ khi bạn bấm nhận và được phân công thì khung giờ mới được giữ chính thức.</p></div><div className="invitation-list">{invitations.map(item=><article className="invitation-card" key={item.id}><header><span className={`invitation-status ${item.status.toLowerCase()}`}>{item.status==="Invited"?"Chờ phản hồi":item.status}</span><small>Hết hạn {new Date(item.expiresAt).toLocaleString("vi-VN")}</small></header><h2>{item.service}</h2><p><MapPin/>{item.addressSnapshot}</p><p><Clock3/>{new Date(item.scheduledStartAt).toLocaleString("vi-VN")} — {new Date(item.scheduledEndAt).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"})}</p>{item.customerRequest&&<p><BriefcaseBusiness/>Yêu cầu: {item.customerRequest}</p>}<div><span>{item.requiredWorkers} người</span><span>{item.distanceMetersAtInvitation?`${(item.distanceMetersAtInvitation/1000).toFixed(1)} km`:"Chưa rõ khoảng cách"}</span><strong>{money(item.estimatedTotal)}</strong></div>{item.status==="Invited"&&new Date(item.expiresAt)>new Date()&&<footer><button disabled={saving} onClick={()=>void respond(item.id,false)}>Từ chối</button><button className="button" disabled={saving} onClick={()=>void respond(item.id,true)}>Đồng ý nhận</button></footer>}</article>)}{!invitations.length&&<div className="portal-empty">Chưa có lời mời phù hợp.</div>}</div></>}
  {tab==="notifications"&&<><div className="portal-title"><span>Thông báo</span><h1>Thông báo của bạn</h1><p>Lời mời vẫn nằm ở đây khi bạn đăng xuất hoặc đóng website.</p></div><section className="portal-card notification-list">{notifications.map(item=><div key={item.id} className={item.isRead?"":"unread"}><Bell/><span><strong>{item.title}</strong><p>{item.message}</p><small>{new Date(item.createdAt).toLocaleString("vi-VN")}</small></span></div>)}{!notifications.length&&<div className="portal-empty">Chưa có thông báo.</div>}</section></>}
 </div></section></main>;
}
